# Generated by Django 2.1 on 2020-03-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20200304_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
