# Generated by Django 2.1 on 2020-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_auto_20200304_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='forDiscussion',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='text',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='type',
        ),
        migrations.AlterField(
            model_name='claim',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
