# Generated by Django 2.1 on 2020-03-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_auto_20200304_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='debate.Claim'),
        ),
        migrations.AddField(
            model_name='claim',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='type',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
