# Generated by Django 2.1 on 2020-03-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0006_auto_20200304_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='for_discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='debate.Discussion'),
            preserve_default=False,
        ),
    ]
