# Generated by Django 2.1 on 2020-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0010_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='suggested',
            field=models.IntegerField(default=0),
        ),
    ]
