# Generated by Django 2.1 on 2020-03-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0011_claim_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='for_discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.Discussion'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Claim'),
        ),
    ]
