export const GET_DISCUSSIONS = "GET_DISCUSSIONS";
export const DELETE_DISCUSSION = "DELETE_DISCUSSION";
export const ADD_DISCUSSION = "ADD_DISCUSSION";
export const ADD_DISCUSSION_SUCCESS = "ADD_DISCUSSION_SUCCESS";
export const ADD_DISCUSSION_FAIL = "ADD_DISCUSSION_SUCCESS";
export const SELECT_DISCUSSION = "SELECT_DISCUSSION";

export const ADD_CLAIM = "ADD_CLAIM";
export const SELECT_CLAIM = "SELECT_CLAIM";
export const UPDATE_CLAIMS = "UPDATE_CLAIMS";



export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAR_LEADS = 'CLEAR_LEADS';

export const GET_USER_DISCUSSIONS = 'GET_USER_DISCUSSIONS';
export const GET_USER_CLAIMS = 'GET_USER_CLAIMS';

export const ADD_CLAIM_DIALOG = 'ADD_CLAIM_DIALOG';
export const SELECT_TYPE = 'SELECT_TYPE'
export const ADD_MANAGER_DIALOG = 'ADD_MANAGER_DIALOG'
export const EDIT_DISCUSSION = 'EDIT_DISCUSSION'